/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danish
 */
public class Feedback extends javax.swing.JFrame {

    /**
     * Creates new form OrderManagement
     */
    public Feedback() throws FileNotFoundException {
        initComponents();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        feedbackTextField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        sendButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        feedbackTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1208, 709));
        setMinimumSize(new java.awt.Dimension(1208, 709));
        setPreferredSize(new java.awt.Dimension(1208, 709));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 40));

        feedbackTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        feedbackTextField.setText("Enter Your Feedback");
        feedbackTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                feedbackTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                feedbackTextFieldFocusLost(evt);
            }
        });
        getContentPane().add(feedbackTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 450, 50));

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, 130, 50));

        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        getContentPane().add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 130, 50));

        sendButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        sendButton.setText("SEND");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 130, 50));

        feedbackTable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        feedbackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Feedback"
            }
        ));
        jScrollPane2.setViewportView(feedbackTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 600, 410));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 370, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 640, 450));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 640, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
         try {
            refresh();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
       DefaultTableModel model =(DefaultTableModel)feedbackTable.getModel();
       if(feedbackTable.getSelectedRowCount()==1){
            model.removeRow(feedbackTable.getSelectedRow());
              
              JOptionPane.showMessageDialog(null, "Deleted Successfully");    
       }
       else
       {
           if(feedbackTable.getSelectedRowCount()==0){
           JOptionPane.showMessageDialog(null, "Table is empty");
           }
           else{
           JOptionPane.showMessageDialog(null, "Please select single row for delete");
           }
       }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        send();
    }//GEN-LAST:event_sendButtonActionPerformed

    private void feedbackTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_feedbackTextFieldFocusGained
        if(feedbackTextField.getText().equals("Enter Your Feedback"))
        {
            feedbackTextField.setText("");
        }
    }//GEN-LAST:event_feedbackTextFieldFocusGained

    private void feedbackTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_feedbackTextFieldFocusLost
        if(feedbackTextField.getText().equals(""))
        {
            feedbackTextField.setText("Enter Your Feedback");   
        }
    }//GEN-LAST:event_feedbackTextFieldFocusLost

    private void refresh() throws FileNotFoundException{
  DefaultTableModel model =(DefaultTableModel)feedbackTable.getModel();
  model.setNumRows(0);        
    String filePath="D:\\Courier System\\Courier System\\src\\TextFiles\\feedback.txt";
    File file=new File(filePath);
    
              FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
           // DefaultTableModel model = (DefaultTableModel)userJTable.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
    }    
    
    private void send() {
        
       String feedback=feedbackTextField.getText();
   

       try{
           FileWriter Writer=new FileWriter("D:\\Courier System\\Courier System\\src\\TextFiles\\feedback.txt",true);
           Writer.write(feedback);
           Writer.write(System.getProperty("line.separator"));
           Writer.close();
           JOptionPane.showMessageDialog (null,"Successfully Added");
           setVisible(false);
           new Feedback().setVisible(true);
           refresh();
       }catch(Exception e){
       e.printStackTrace();
       }
       
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Feedback().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Feedback.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable feedbackTable;
    private javax.swing.JTextField feedbackTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
