/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Danish
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordPasswordField = new javax.swing.JPasswordField();
        usernameTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        loginAsManagerButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        loginAsDeliveryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1228, 632));
        setMinimumSize(new java.awt.Dimension(1228, 632));
        setPreferredSize(new java.awt.Dimension(1228, 632));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        titleLabel.setText("Welcome  to the Courier System ");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 690, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 810, 90));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showPasswordCheckBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        showPasswordCheckBox.setText("Show Password");
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });
        jPanel3.add(showPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setText("Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setText("Password");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, -1));

        passwordPasswordField.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        passwordPasswordField.setText("Enter Password");
        passwordPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordPasswordFieldFocusLost(evt);
            }
        });
        jPanel3.add(passwordPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 320, -1));

        usernameTextField.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        usernameTextField.setText("Enter Username");
        usernameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextFieldFocusLost(evt);
            }
        });
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 320, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 640, 380));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel4.setForeground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginAsManagerButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        loginAsManagerButton.setText("Login As Manager");
        loginAsManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAsManagerButtonActionPerformed(evt);
            }
        });
        jPanel4.add(loginAsManagerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 60));

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel4.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 130, 60));

        loginAsDeliveryButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        loginAsDeliveryButton.setText("Login As Delivery");
        loginAsDeliveryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAsDeliveryButtonActionPerformed(evt);
            }
        });
        jPanel4.add(loginAsDeliveryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 220, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 640, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed

    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void loginAsManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAsManagerButtonActionPerformed
        if(usernameTextField.getText().equals("courier") && passwordPasswordField.getText().equals("1234"))
        {
            setVisible(false);
            new HomePage().setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Incorrect unername or password");
    }//GEN-LAST:event_loginAsManagerButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
     usernameTextField.setText("");
     passwordPasswordField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        if(showPasswordCheckBox.isSelected())
        {
            passwordPasswordField.setEchoChar((char)0);
        }
        else
            passwordPasswordField.setEchoChar('*');
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed

    private void usernameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFieldFocusGained
      
        if(usernameTextField.getText().equals("Enter Username"))
        {
            usernameTextField.setText("");
            
        }
    }//GEN-LAST:event_usernameTextFieldFocusGained

    private void usernameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFieldFocusLost
        
        if(usernameTextField.getText().equals(""))
        {
            usernameTextField.setText("Enter Username");
           
        }
    }//GEN-LAST:event_usernameTextFieldFocusLost

    private void passwordPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordPasswordFieldFocusLost
       
        if(passwordPasswordField.getText().equals(""))
        {
            passwordPasswordField.setText("Enter Password");
          
        }
    }//GEN-LAST:event_passwordPasswordFieldFocusLost

    private void passwordPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordPasswordFieldFocusGained
       
        if(passwordPasswordField.getText().equals("Enter Password"))
        {
            passwordPasswordField.setText("");
            
        }
    }//GEN-LAST:event_passwordPasswordFieldFocusGained

    private void loginAsDeliveryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAsDeliveryButtonActionPerformed
        if(usernameTextField.getText().equals("delivery") && passwordPasswordField.getText().equals("1234"))
        {
            setVisible(false);
            new DeliveryHome().setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Incorrect unername or password");
          
    }//GEN-LAST:event_loginAsDeliveryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton loginAsDeliveryButton;
    private javax.swing.JButton loginAsManagerButton;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
