/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.io.*;
import static java.util.Locale.*;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Danish
 */
public class OrderManagement extends javax.swing.JFrame {

    /**
     * Creates new form OrderManagement
     */
    public OrderManagement() throws FileNotFoundException {
        initComponents();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        oderTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        phoneNoTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalPriceTextField = new javax.swing.JTextField();
        timeAndDateTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sizeTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        orderIdTextField = new javax.swing.JTextField();
        statusTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        calculateButton = new javax.swing.JButton();
        generateIdButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1324, 762));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 29, 100, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, -1));

        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        getContentPane().add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 570, 130, 50));

        oderTable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        oderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer  Name", "Phone Number", "Address", "Order ID", "Size", "Date & Time", "Total Price", "Status"
            }
        ));
        oderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oderTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(oderTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 730, 430));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Order ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 30));

        customerNameTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(customerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 230, 30));

        phoneNoTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(phoneNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 230, 30));

        AddressTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(AddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 230, 30));

        addButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 100, 50));

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 100, 50));

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 100, 50));

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, 100, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Status");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 70, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Total Price (RM)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 150, 30));

        totalPriceTextField.setEditable(false);
        totalPriceTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(totalPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 230, 30));

        timeAndDateTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(timeAndDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 230, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Date & Time");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        sizeTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(sizeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 230, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Size (kg)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 80, -1));

        orderIdTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(orderIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 230, 30));

        statusTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(statusTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 230, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 1260, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calculateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });
        jPanel2.add(calculateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 100, -1));

        generateIdButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generateIdButton.setText("Generate ID");
        generateIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateIdButtonActionPerformed(evt);
            }
        });
        jPanel2.add(generateIdButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 500, 450));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel1.setText("Manage Order Here");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 250, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 550, 50));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addorderManagement();
    }//GEN-LAST:event_addButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed

        try {
            refresh();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(OrderManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void oderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oderTableMouseClicked
        int i=oderTable.getSelectedRow();
        TableModel model=oderTable.getModel();
        customerNameTextField.setText(model.getValueAt(i, 0).toString());
        phoneNoTextField.setText(model.getValueAt(i, 1).toString());
        AddressTextField.setText(model.getValueAt(i, 2).toString());
        orderIdTextField.setText(model.getValueAt(i, 3).toString());
        sizeTextField.setText(model.getValueAt(i, 4).toString());
        timeAndDateTextField.setText(model.getValueAt(i, 5).toString());
        totalPriceTextField.setText(model.getValueAt(i, 6).toString());
        statusTextField.setText(model.getValueAt(i, 7).toString());        
     
    }//GEN-LAST:event_oderTableMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
       DefaultTableModel model =(DefaultTableModel)oderTable.getModel();
       if(oderTable.getSelectedRowCount()==1){
            model.removeRow(oderTable.getSelectedRow());
              
              JOptionPane.showMessageDialog(null, "Deleted Successfully");    
       }
       else
       {
           if(oderTable.getSelectedRowCount()==0){
           JOptionPane.showMessageDialog(null, "Table is empty");
           }
           else{
           JOptionPane.showMessageDialog(null, "Please select single row for delete");
           }
       }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
       DefaultTableModel model =(DefaultTableModel)oderTable.getModel();
       if(oderTable.getSelectedRowCount()==1){
           
       String customerName=customerNameTextField.getText();
       String phoneNo=phoneNoTextField.getText();
       String address=AddressTextField.getText();
       String orderId=orderIdTextField.getText();
       String size=sizeTextField.getText();
       String dateAndTime=timeAndDateTextField.getText();
       String totalPrice=totalPriceTextField.getText();
       String status=statusTextField.getText(); 
              
              
              model.setValueAt(customerName, oderTable.getSelectedRow(), 0);
              model.setValueAt(phoneNo, oderTable.getSelectedRow(), 1);
              model.setValueAt(address, oderTable.getSelectedRow(), 2);
              model.setValueAt(orderId, oderTable.getSelectedRow(), 3);
              model.setValueAt(size, oderTable.getSelectedRow(), 4);
              model.setValueAt(dateAndTime, oderTable.getSelectedRow(), 5);
              model.setValueAt(totalPrice, oderTable.getSelectedRow(), 6);
              model.setValueAt(status, oderTable.getSelectedRow(), 7);              
              
 
              
              JOptionPane.showMessageDialog(null, "Updated Successfully");    
       }
       else
       {
           if(oderTable.getSelectedRowCount()==0){
           JOptionPane.showMessageDialog(null, "Table is empty");
           }
           else{
           JOptionPane.showMessageDialog(null, "Please select single row for update");
           }
       }
       
    }//GEN-LAST:event_updateButtonActionPerformed

    private void generateIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateIdButtonActionPerformed
        Random rand = new Random();
        int id = rand.nextInt(1000);
        orderIdTextField.setText(id+"");
    }//GEN-LAST:event_generateIdButtonActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        int size=Integer.parseInt(sizeTextField.getText());
        int totalPrice=size*3;
        totalPriceTextField.setText(totalPrice+"");
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        customerNameTextField.setText("");
        phoneNoTextField.setText("");
        AddressTextField.setText("");
        orderIdTextField.setText("");
        sizeTextField.setText("");
        timeAndDateTextField.setText("");
        totalPriceTextField.setText("");
        statusTextField.setText(""); 
    }//GEN-LAST:event_clearButtonActionPerformed
private void refresh() throws FileNotFoundException{
  DefaultTableModel model =(DefaultTableModel)oderTable.getModel();
  model.setNumRows(0);        
    String filePath="D:\\Courier System\\Courier System\\src\\TextFiles\\orderManagement.txt";
    File file=new File(filePath);
    
              FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
           
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(",");
                model.addRow(row);
            }    
    }
    private void addorderManagement() {
       
       String customerName=customerNameTextField.getText();
       String phoneNo=phoneNoTextField.getText();
       String address=AddressTextField.getText();
       String orderId=orderIdTextField.getText();
       String size=sizeTextField.getText();
       String dateAndTime=timeAndDateTextField.getText();
       String totalPrice=totalPriceTextField.getText();
       String status=statusTextField.getText();       
       
       try{
           FileWriter Writer=new FileWriter("D:\\Courier System\\Courier System\\src\\TextFiles\\orderManagement.txt",true);
           Writer.write(""+customerName+","+phoneNo+","+address+","+orderId+","+size+","+dateAndTime+","+totalPrice+","+status);
           Writer.write(System.getProperty("line.separator"));
           Writer.close();
           JOptionPane.showMessageDialog (null,"Successfully Added");
           setVisible(false);
           new OrderManagement().setVisible(true);
           refresh();
       }catch(Exception e){
       e.printStackTrace();
       }
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new OrderManagement().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(OrderManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton generateIdButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable oderTable;
    private javax.swing.JTextField orderIdTextField;
    private javax.swing.JTextField phoneNoTextField;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField sizeTextField;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JTextField timeAndDateTextField;
    private javax.swing.JTextField totalPriceTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables


}
