/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import static java.util.Locale.*;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Danish
 */
public class ReportManagement extends javax.swing.JFrame {

    /**
     * Creates new form OrderManagement
     */
    public ReportManagement() throws FileNotFoundException {
        initComponents();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        oderTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        phoneNoTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        totalPriceTextField = new javax.swing.JTextField();
        timeAndDateTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sizeTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        orderIdTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        reciptTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1324, 762));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, -1));

        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        getContentPane().add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 430, 160, 60));

        oderTable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        oderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer  Name", "Phone Number", "Address", "Order ID", "Size", "Date & Time", "Total Price"
            }
        ));
        oderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oderTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(oderTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 730, 300));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Order ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 30));

        customerNameTextField.setEditable(false);
        customerNameTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(customerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 230, 30));

        phoneNoTextField.setEditable(false);
        phoneNoTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(phoneNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 230, 30));

        AddressTextField.setEditable(false);
        AddressTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(AddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 230, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Total Price (RM)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 150, 30));

        totalPriceTextField.setEditable(false);
        totalPriceTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(totalPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 230, 30));

        timeAndDateTextField.setEditable(false);
        timeAndDateTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(timeAndDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 230, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Date & Time");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 110, -1));

        sizeTextField.setEditable(false);
        sizeTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(sizeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 230, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Size (kg)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 90, -1));

        orderIdTextField.setEditable(false);
        orderIdTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(orderIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 230, 30));

        reciptTextArea.setEditable(false);
        reciptTextArea.setColumns(20);
        reciptTextArea.setRows(5);
        jScrollPane2.setViewportView(reciptTextArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 400, 230));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel1.setText("Report Management");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 260, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 630, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 500, 320));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 760, 320));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Generate Recipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Print Recipt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 220, 160));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 420, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed

        try {
            refresh();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ReportManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void oderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oderTableMouseClicked
        int i=oderTable.getSelectedRow();
        TableModel model=oderTable.getModel();
        customerNameTextField.setText(model.getValueAt(i, 0).toString());
        phoneNoTextField.setText(model.getValueAt(i, 1).toString());
        AddressTextField.setText(model.getValueAt(i, 2).toString());
        orderIdTextField.setText(model.getValueAt(i, 3).toString());
        sizeTextField.setText(model.getValueAt(i, 4).toString());
        timeAndDateTextField.setText(model.getValueAt(i, 5).toString());
        totalPriceTextField.setText(model.getValueAt(i, 6).toString());
            

    }//GEN-LAST:event_oderTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      reciptTextArea.setText(" ");
        String customerName=customerNameTextField.getText();
       String phoneNo=phoneNoTextField.getText();
       String address=AddressTextField.getText();
       String orderId=orderIdTextField.getText();
       String size=sizeTextField.getText();
       String dateAndTime=timeAndDateTextField.getText();
       String totalPrice=totalPriceTextField.getText();
        
    //============================================================================
        int refs=1235 + (int) (Math.random()*4238);
       // int ref = (refs);
    //============================================================================
            Calendar timer = Calendar.getInstance();
            timer.getTime();
            SimpleDateFormat tTime = new SimpleDateFormat("hh:mm:ss");
            tTime.format(timer.getTime());
            SimpleDateFormat TDate = new SimpleDateFormat("dd-MMM-yyyy");
            TDate.format(timer.getTime());
    //============================================================================
            
            
        
        reciptTextArea.append(  "************************************************************"
                                + "\n*\t                Receipt  \t           *\n" +
                                "************************************************************" +
                                "\nCustomer Name:\t " + customerName +
                                "\nPhone Number:\t\t " + phoneNo +
                                "\nAddress:\t\t " + address +
                                "\nOrder ID:\t\t " + orderId +
                                "\nSize:\t\t " + size +
                                "\nDate And Time:\t\t " + dateAndTime +
                                "\nTotal Price:\t\t " + totalPrice +
                                "\n************************************************************" +
                                "\nDate: " + TDate.format(timer.getTime()) +
                                "\tTime: "+ tTime.format(timer.getTime()) +
                                "\n\tThank You");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     PrinterJob job = PrinterJob.getPrinterJob();
     
     boolean ok = job.printDialog();
     if (ok) {
         try {
              job.print();
         } catch (PrinterException ex) {

         }
     }
    }//GEN-LAST:event_jButton2ActionPerformed
private void refresh() throws FileNotFoundException{
  DefaultTableModel model =(DefaultTableModel)oderTable.getModel();
  model.setNumRows(0);        
    String filePath="D:\\Courier System\\Courier System\\src\\TextFiles\\orderManagement.txt";
    File file=new File(filePath);
    
              FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
           
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(",");
                model.addRow(row);
            }    
    }
    private void addorderManagement() {
       
       String customerName=customerNameTextField.getText();
       String phoneNo=phoneNoTextField.getText();
       String address=AddressTextField.getText();
       String orderId=orderIdTextField.getText();
       String size=sizeTextField.getText();
       String dateAndTime=timeAndDateTextField.getText();
       String totalPrice=totalPriceTextField.getText();
            
       
       try{
           FileWriter Writer=new FileWriter("D:\\Courier System\\Courier System\\src\\TextFiles\\orderManagement.txt",true);
           Writer.write(""+customerName+","+phoneNo+","+address+","+orderId+","+size+","+dateAndTime+","+totalPrice);
           Writer.write(System.getProperty("line.separator"));
           Writer.close();
           JOptionPane.showMessageDialog (null,"Successfully Added");
           setVisible(false);
           new ReportManagement().setVisible(true);
           refresh();
       }catch(Exception e){
       e.printStackTrace();
       }
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ReportManagement().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ReportManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable oderTable;
    private javax.swing.JTextField orderIdTextField;
    private javax.swing.JTextField phoneNoTextField;
    private javax.swing.JTextArea reciptTextArea;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField sizeTextField;
    private javax.swing.JTextField timeAndDateTextField;
    private javax.swing.JTextField totalPriceTextField;
    // End of variables declaration//GEN-END:variables


}
