/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Danish
 */
public class UserManagement extends javax.swing.JFrame {

    /**
     * Creates new form OrderManagement
     */
    public UserManagement() throws FileNotFoundException {
        initComponents();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userJTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        roleTextField = new javax.swing.JTextField();
        passwordPasswordField = new javax.swing.JPasswordField();
        phoneNoTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        viewPasswordCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1324, 762));
        setMinimumSize(new java.awt.Dimension(1324, 762));
        setPreferredSize(new java.awt.Dimension(1324, 762));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Phone Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        userJTable.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        userJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "PhoneNumber", "Password", "Role"
            }
        ));
        userJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userJTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 670, 420));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        addButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 120, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel1.setText("USER ACCOUNT MANAGEMENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 650, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        jPanel2.add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 180, 70));

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel2.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 120, 40));

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel2.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 120, 40));

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel2.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 120, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 1250, 90));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 690, 440));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roleTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel4.add(roleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 230, 40));

        passwordPasswordField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel4.add(passwordPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 230, 40));

        phoneNoTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel4.add(phoneNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 230, 40));

        emailTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel4.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 230, 40));

        nameTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel4.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 230, 40));

        viewPasswordCheckBox.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        viewPasswordCheckBox.setText("View");
        viewPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPasswordCheckBoxActionPerformed(evt);
            }
        });
        jPanel4.add(viewPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("Role");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 550, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addUerManagement();
    }//GEN-LAST:event_addButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed

        try {
            refresh();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void userJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userJTableMouseClicked
        int i=userJTable.getSelectedRow();
        TableModel model=userJTable.getModel();
        nameTextField.setText(model.getValueAt(i, 0).toString());
        emailTextField.setText(model.getValueAt(i, 1).toString());
        phoneNoTextField.setText(model.getValueAt(i, 2).toString());
        passwordPasswordField.setText(model.getValueAt(i, 3).toString());
        if(model.getValueAt(i, 4)==null)
            roleTextField.setText("");
        else
        roleTextField.setText(model.getValueAt(i, 4).toString());

    }//GEN-LAST:event_userJTableMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
       DefaultTableModel model =(DefaultTableModel)userJTable.getModel();
       if(userJTable.getSelectedRowCount()==1){
            model.removeRow(userJTable.getSelectedRow());
              
              JOptionPane.showMessageDialog(null, "Deleted Successfully");    
       }
       else
       {
           if(userJTable.getSelectedRowCount()==0){
           JOptionPane.showMessageDialog(null, "Table is empty");
           }
           else{
           JOptionPane.showMessageDialog(null, "Please select single row for delete");
           }
       }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
       DefaultTableModel model =(DefaultTableModel)userJTable.getModel();
       if(userJTable.getSelectedRowCount()==1){
              String name=nameTextField.getText();
              String email=emailTextField.getText();
              String phone=phoneNoTextField.getText();
              String pass=passwordPasswordField.getText();
              String role=roleTextField.getText();
              
              model.setValueAt(name, userJTable.getSelectedRow(), 0);
              model.setValueAt(email, userJTable.getSelectedRow(), 1);
              model.setValueAt(phone, userJTable.getSelectedRow(), 2);
              model.setValueAt(pass, userJTable.getSelectedRow(), 3);
              model.setValueAt(role, userJTable.getSelectedRow(), 4);
              
              JOptionPane.showMessageDialog(null, "Updated Successfully");    
       }
       else
       {
           if(userJTable.getSelectedRowCount()==0){
           JOptionPane.showMessageDialog(null, "Table is empty");
           }
           else{
           JOptionPane.showMessageDialog(null, "Please select single row for update");
           }
       }
       
    }//GEN-LAST:event_updateButtonActionPerformed

    private void viewPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPasswordCheckBoxActionPerformed
             if(viewPasswordCheckBox.isSelected())
        {
            passwordPasswordField.setEchoChar((char)0);
        }
        else
            passwordPasswordField.setEchoChar('*');
    }//GEN-LAST:event_viewPasswordCheckBoxActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
       
        nameTextField.setText("");
        emailTextField.setText("");
        phoneNoTextField.setText("");
        passwordPasswordField.setText("");
        roleTextField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed
    private void refresh() throws FileNotFoundException{
  DefaultTableModel model =(DefaultTableModel)userJTable.getModel();
  model.setNumRows(0);        
    String filePath="D:\\Courier System\\Courier System\\src\\TextFiles\\userManagement.txt";
    File file=new File(filePath);
    
              FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
           // DefaultTableModel model = (DefaultTableModel)userJTable.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }
            
    
    }
    private void addUerManagement() {
       
       String name=nameTextField.getText();
       String email=emailTextField.getText();
       String phone=phoneNoTextField.getText();
       String pass=passwordPasswordField.getText();
       String role=roleTextField.getText();
       

       try{
           FileWriter Writer=new FileWriter("D:\\Courier System\\Courier System\\src\\TextFiles\\userManagement.txt",true);
           Writer.write(""+name+" "+email+" "+phone+" "+pass+" "+role);
           Writer.write(System.getProperty("line.separator"));
           Writer.close();
           JOptionPane.showMessageDialog (null,"Successfully Added");
           setVisible(false);
           new UserManagement().setVisible(true);
           refresh();
       }catch(Exception e){
       e.printStackTrace();
       }
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserManagement().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(UserManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JTextField phoneNoTextField;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField roleTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JTable userJTable;
    private javax.swing.JCheckBox viewPasswordCheckBox;
    // End of variables declaration//GEN-END:variables


}
